version: '3.9'

services:
  dbpostgres:
    image: postgres:latest
    container_name: garden_store_db
    restart: always
    env_file:
      - .env.development.local
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: